### PR TITLE
removing "-flto"

### PR DESCRIPTION
**Pull request by codeM-X**
removing -flto to fix compiler error (windows 10 + gcc 8.2.1 (mingw) 12/12/2018)

### CODE REVIEW

**Comment by Wolfvak** [comment]
Personally, I'd say create an issue on devkitpro/buildscripts and push this to a 'windows-compat' branch instead...

**Comment by d0k3** [comment]
@codeM-X - take it slow. One major change per pull request. Don't keep pushing commits. We're still discussing what to do about the `-flo` thing (yes, that's a devkitPro on Windows issue).

The config from NAND thing hasn't been discussed yet.

**Comment by codeM-X** [comment]
Didn't wanted to puck the update to config.c, i am new to github :).

**Comment by d0k3** [comment]
Yeah, it's alright. Just stop pushing commits to that branch.

**Comment by profi200** [comment]
And yeah, as i mentioned in the Luma issue by you this is a workaround. It is not convenient but using the Linux Variant of devkitARM in WSL on Windows 10 is an option. Or if you have Linux already in a VM or installed compile on that.

We may or may not change the makefile to work around this in the meantime. Not sure yet.

@d0k3 
Be careful what to say :p It's actually a GCC bug. Not the fault of devkitPro.

**Comment by codeM-X** [comment]
Ok sry I will always commit to the branch I see... dont know why ahahha sry for the inconvenience :/

**Pull request closed without merging**
